name: "Update category documentation"
on:
  repository_dispatch:
    types: [category-doc-update]

jobs:
  update_category_docs:
    name: "Update category documentation"
    # Only one job at a time, to avoid confflicts.
    concurrency: doc-update
    runs-on: "ubuntu-latest"
    permissions: write-all
    env:
      FROM_REPO: ${{ github.event.client_payload.repo }}
      FROM_TAG: ${{ github.event.client_payload.tag }}
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4
        with:
          ref: main

      - name: "Download the new content"
        # TODO
        run: |
          CATEGORY_ID="${FROM_REPO#RiverBench/category-}"
          VERSION_ID="${FROM_TAG#v}"
          mkdir -p "docs/categories/${CATEGORY_ID}"
          cd "docs/categories/${CATEGORY_ID}"
          rm -rf "./${VERSION_ID}" || true
          mkdir "./${VERSION_ID}"
          cd "./${VERSION_ID}"
          wget "https://github.com/${FROM_REPO}/releases/download/${FROM_TAG}/docs.tar.gz"
          tar -xzvf docs.tar.gz
          mv ./category/* . || true
          rm -r ./category || true
          rm docs.tar.gz

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: ${{ format('Automatic update of {0} ({1})', github.event.client_payload.repo, github.event.client_payload.tag) }}
          default_author: github_actions
          add: docs/categories/*
          pull: '--rebase --autostash'
          push: true

      - name: "Trigger doc compilation"
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_DOC_REPO_HOOKS }}
          event-type: compile-docs
