name: Compile documentation
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [compile-docs]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate nav
        uses: docker://ghcr.io/riverbench/ci-worker:main
        with:
          args: ci-worker nav-gen . mkdocs_2.yml

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Deploy site
        run: |
          mv mkdocs_2.yml mkdocs.yml
          TAG='${{ inputs.tag }}'
          git fetch origin gh-pages --depth=1
          git config user.name ci-bot
          git config user.email ci-bot@example.com
          if [[ $TAG == v* ]] ; then
            mike deploy --push --update-aliases "${TAG#v}" stable
          else
            mike deploy --push --update-aliases dev latest
          fi
