name: Compile documentation
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [compile-docs]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/riverbench/ci-worker:main
    steps:
      - uses: actions/checkout@v3

      - name: Generate nav
        run: |
          ci-worker nav-gen . mkdocs_2.yml
          mv mkdocs_2.yml mkdocs.yml

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Deploy site
        run: mkdocs gh-deploy --force
