name: Compile documentation
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [compile-docs]

permissions:
  contents: write

jobs:
  deploy:
    env:
      RELEASE_TAG: ${{ github.event.client_payload.tag }}
    runs-on: ubuntu-latest
    steps:
        # TODO: stable releases – use stable branch

      - uses: actions/checkout@v4

      - name: Generate nav
        uses: docker://ghcr.io/riverbench/ci-worker:main
        with:
          args: ci-worker nav-gen . mkdocs_2.yml

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Deploy site
        run: |
          mv mkdocs_2.yml mkdocs.yml
          git fetch origin gh-pages --depth=1
          git config user.name ci-bot
          git config user.email ci-bot@example.com
          if [[ $RELEASE_TAG == v* ]] ; then
            mike deploy --push --update-aliases "${RELEASE_TAG#v}" stable
          else
            mike deploy --push --update-aliases dev latest
          fi
