name: "Update schema documentation"
on:
  repository_dispatch:
    types: [schema-doc-update]

jobs:
  update-schema-docs:
    name: "Update schema documentation"
    # Only one job at a time, to avoid conflicts.
    concurrency: doc-update
    runs-on: "ubuntu-latest"
    permissions: write-all
    env:
      FROM_TAG: ${{ github.event.client_payload.tag }}
    steps:
      - name: "Checkout the repository (main)"
        if: ${{ github.event.client_payload.tag == 'dev' }}
        uses: actions/checkout@v4
        with:
          ref: main

      - name: "Checkout the repository (stable)"
        if: ${{ github.event.client_payload.tag != 'dev' }}
        uses: actions/checkout@v4
        with:
          ref: stable

      - name: "Download the new content"
        run: |
          cd "docs/schema"
          wget "https://github.com/RiverBench/schema/releases/download/${FROM_TAG}/docs.tar.gz"
          mv index.md .index.md
          rm -f ./* || true
          mv .index.md index.md
          tar -xzvf docs.tar.gz ./documentation.md ./metadata.md
          rm docs.tar.gz

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: ${{ format('Automatic update of schema docs ({1})', github.event.client_payload.repo, github.event.client_payload.tag) }}
          default_author: github_actions
          add: docs/schema/*
          pull: '--rebase --autostash'
          push: true

      - name: "Trigger doc compilation"
        if: ${{ github.event.client_payload.tag == 'dev' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_DOC_REPO_HOOKS }}
          event-type: compile-docs
          client-payload: '{ "tag": "dev" }'
